monolog:
    handlers:
        custom_log:
            type: stream
            path: "%kernel.logs_dir%/app_log.%kernel.environment%.log"
            level: debug
            channels: ["app"]

        rq_status:
            type: stream
            path: "%kernel.logs_dir%/rq_status.%kernel.environment%.log"
            level: debug
            channels: ["request"]
        
        rq_error:
            type: stream
            path: "%kernel.logs_dir%/rq_error.%kernel.environment%.log"
            level: error
            channels: ["request"]
        
        doctrine_status:
            type: stream
            path: "%kernel.logs_dir%/doctrine_status.%kernel.environment%.log"
            level: debug
            channels: ["doctrine"]
        
        doctrine_error:
            type: stream
            path: "%kernel.logs_dir%/doctrine_error.%kernel.environment%.log"
            level: error
            channels: ["doctrine"]

        php_error:
            type: stream
            path: "%kernel.logs_dir%/fatal_error.%kernel.environment%.log"
            level: error
            channels: ["!event"]
        
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
